repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: '(\.txt|\.yaml)'
    -   id: trailing-whitespace
        exclude: '(\.txt|\.yaml)'
    -   id: mixed-line-ending
        exclude: \.txt
    -   id: debug-statements
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.4
  hooks:
    - id: ruff
      args: ["--config", "embedding_engine/pyproject.toml"]
    - id: ruff-format
      args: ["--config", "embedding_engine/pyproject.toml"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args: ["--config-file=embedding_engine/pyproject.toml", ]
